const strObjects = {
    email: "Email",
    login: "Login",
    password: "Password",
    welcome: "Welcome",
    please_login: "Please login",
    username: "Username",
    username_regex: /^[a-zA-Z0-9_]{3,20}$/,
    name: "Name",
    error_404: "404",
    uh_oh_you_re_lost: "UH OH! You're lost.",
    the_page_you_are_looking_for: "The page you are looking for does not exist. How you got here is a mystery. But you can click the button below to go back to the homepage.",
    filer: "FILER",
    place_holder_full_name:"e.g. Rajat Tripathi",
    place_holder_password:"e.g. Cool_App@23XXXXXXXX",
    place_holder_username:"e.g. Shubham_1994",
    place_holder_email:"e.g. rajat23@filer.com",
    entershortname:"Enter short name..",
    signup: "Signup",
    enter_a_valid_username: "Enter a valid username",
    // enter_a_valid_password: "Enter a valid password (8-20 characters, atleast one alphabet, atleast one number and atleast one characters from '@$!%*#?&' ",
    enter_a_valid_password: "Enter a valid password",
    enter_a_valid_email: "Enter a valid email",
    password_regex: /^(?=.*[A-Za-z])(?=.*\d)(?=.*[@$!%*#?&])[A-Za-z\d@$!%*#?&]{8,20}$/,
    first_name: "First name",
    enter_a_first_name:"Enter a first name",
    place_holder_first_name:"e.g. Rajat",
    last_name: "Last name",
    place_holder_last_name:"e.g. Tripathi",
    confirm_password: "Confirm password",
    password_confrim_password_dont_match: "Password and Confrim password don't match",
    please_provide_all_the_inputs_properly: "Please provide all the inputs properly",
    success_message: "Success",
    error_message: "Uh Oh! Something went wrong"

}

export { strObjects }